// sort by Location for results of free text box
// could split into smaller arrays based on country / continent for quicker search?

// find a more appropriate name

const CountryData = [
  {ID:1,CountryCode:"DZ",Location:"Algeria",WOEID:23424740,Continent:"Africa",Country:"Algeria"},
  {ID:2,CountryCode:"DZ",Location:"Algiers",WOEID:1253079,Continent:"Africa",Country:"Algeria"},
  {ID:3,CountryCode:"AR",Location:"Argentina",WOEID:23424747,Continent:"South America",Country:"Argentina"},
  {ID:4,CountryCode:"AR",Location:"Buenos Aires",WOEID:468739,Continent:"South America",Country:"Argentina"},
  {ID:5,CountryCode:"AR",Location:"Córdoba",WOEID:466861,Continent:"South America",Country:"Argentina"},
  {ID:6,CountryCode:"AR",Location:"Mendoza",WOEID:332471,Continent:"South America",Country:"Argentina"},
  {ID:7,CountryCode:"AR",Location:"Rosario",WOEID:466862,Continent:"South America",Country:"Argentina"},
  {ID:8,CountryCode:"AU",Location:"Adelaide",WOEID:1099805,Continent:"Australia",Country:"Australia"},
  {ID:9,CountryCode:"AU",Location:"Australia",WOEID:23424748,Continent:"Australia",Country:"Australia"},
  {ID:10,CountryCode:"AU",Location:"Brisbane",WOEID:1100661,Continent:"Australia",Country:"Australia"},
  {ID:11,CountryCode:"AU",Location:"Canberra",WOEID:1100968,Continent:"Australia",Country:"Australia"},
  {ID:12,CountryCode:"AU",Location:"Darwin",WOEID:1101597,Continent:"Australia",Country:"Australia"},
  {ID:13,CountryCode:"AU",Location:"Melbourne",WOEID:1103816,Continent:"Australia",Country:"Australia"},
  {ID:14,CountryCode:"AU",Location:"Perth",WOEID:1098081,Continent:"Australia",Country:"Australia"},
  {ID:15,CountryCode:"AU",Location:"Sydney",WOEID:1105779,Continent:"Australia",Country:"Australia"},
  {ID:16,CountryCode:"AT",Location:"Austria",WOEID:23424750,Continent:"Europe",Country:"Austria"},
  {ID:17,CountryCode:"AT",Location:"Vienna",WOEID:551801,Continent:"Europe",Country:"Austria"},
  {ID:18,CountryCode:"BH",Location:"Bahrain",WOEID:23424753,Continent:"Asia",Country:"Bahrain"},
  {ID:19,CountryCode:"BY",Location:"Belarus",WOEID:23424765,Continent:"Europe",Country:"Belarus"},
  {ID:20,CountryCode:"BY",Location:"Brest",WOEID:824382,Continent:"Europe",Country:"Belarus"},
  {ID:21,CountryCode:"BY",Location:"Gomel",WOEID:825978,Continent:"Europe",Country:"Belarus"},
  {ID:22,CountryCode:"BY",Location:"Grodno",WOEID:825848,Continent:"Europe",Country:"Belarus"},
  {ID:23,CountryCode:"BY",Location:"Minsk",WOEID:834463,Continent:"Europe",Country:"Belarus"},
  {ID:24,CountryCode:"BE",Location:"Belgium",WOEID:23424757,Continent:"Europe",Country:"Belgium"},
  {ID:25,CountryCode:"BR",Location:"Belém",WOEID:455820,Continent:"South America",Country:"Brazil"},
  {ID:26,CountryCode:"BR",Location:"Belo Horizonte",WOEID:455821,Continent:"South America",Country:"Brazil"},
  {ID:27,CountryCode:"BR",Location:"Brasília",WOEID:455819,Continent:"South America",Country:"Brazil"},
  {ID:28,CountryCode:"BR",Location:"Brazil",WOEID:23424768,Continent:"South America",Country:"Brazil"},
  {ID:29,CountryCode:"BR",Location:"Campinas",WOEID:455828,Continent:"South America",Country:"Brazil"},
  {ID:30,CountryCode:"BR",Location:"Curitiba",WOEID:455822,Continent:"South America",Country:"Brazil"},
  {ID:31,CountryCode:"BR",Location:"Fortaleza",WOEID:455830,Continent:"South America",Country:"Brazil"},
  {ID:32,CountryCode:"BR",Location:"Goiânia",WOEID:455831,Continent:"South America",Country:"Brazil"},
  {ID:33,CountryCode:"BR",Location:"Guarulhos",WOEID:455867,Continent:"South America",Country:"Brazil"},
  {ID:34,CountryCode:"BR",Location:"Manaus",WOEID:455833,Continent:"South America",Country:"Brazil"},
  {ID:35,CountryCode:"BR",Location:"Porto Alegre",WOEID:455823,Continent:"South America",Country:"Brazil"},
  {ID:36,CountryCode:"BR",Location:"Recife",WOEID:455824,Continent:"South America",Country:"Brazil"},
  {ID:37,CountryCode:"BR",Location:"Rio de Janeiro",WOEID:455825,Continent:"South America",Country:"Brazil"},
  {ID:38,CountryCode:"BR",Location:"Salvador",WOEID:455826,Continent:"South America",Country:"Brazil"},
  {ID:39,CountryCode:"BR",Location:"São Luís",WOEID:455834,Continent:"South America",Country:"Brazil"},
  {ID:40,CountryCode:"BR",Location:"São Paulo",WOEID:455827,Continent:"South America",Country:"Brazil"},
  {ID:41,CountryCode:"CA",Location:"Calgary",WOEID:8775,Continent:"North America",Country:"Canada"},
  {ID:42,CountryCode:"CA",Location:"Canada",WOEID:23424775,Continent:"North America",Country:"Canada"},
  {ID:43,CountryCode:"CA",Location:"Edmonton",WOEID:8676,Continent:"North America",Country:"Canada"},
  {ID:44,CountryCode:"CA",Location:"Montreal",WOEID:3534,Continent:"North America",Country:"Canada"},
  {ID:45,CountryCode:"CA",Location:"Ottawa",WOEID:3369,Continent:"North America",Country:"Canada"},
  {ID:46,CountryCode:"CA",Location:"Quebec",WOEID:3444,Continent:"North America",Country:"Canada"},
  {ID:47,CountryCode:"CA",Location:"Toronto",WOEID:4118,Continent:"North America",Country:"Canada"},
  {ID:48,CountryCode:"CA",Location:"Vancouver",WOEID:9807,Continent:"North America",Country:"Canada"},
  {ID:49,CountryCode:"CA",Location:"Winnipeg",WOEID:2972,Continent:"North America",Country:"Canada"},
  {ID:50,CountryCode:"CL",Location:"Chile",WOEID:23424782,Continent:"South America",Country:"Chile"},
  {ID:51,CountryCode:"CL",Location:"Concepcion",WOEID:349860,Continent:"South America",Country:"Chile"},
  {ID:52,CountryCode:"CL",Location:"Santiago",WOEID:349859,Continent:"South America",Country:"Chile"},
  {ID:53,CountryCode:"CL",Location:"Valparaiso",WOEID:349861,Continent:"South America",Country:"Chile"},
  {ID:54,CountryCode:"CO",Location:"Barranquilla",WOEID:368151,Continent:"South America",Country:"Colombia"},
  {ID:55,CountryCode:"CO",Location:"Bogotá",WOEID:368148,Continent:"South America",Country:"Colombia"},
  {ID:56,CountryCode:"CO",Location:"Cali",WOEID:368149,Continent:"South America",Country:"Colombia"},
  {ID:57,CountryCode:"CO",Location:"Colombia",WOEID:23424787,Continent:"South America",Country:"Colombia"},
  {ID:58,CountryCode:"CO",Location:"Medellín",WOEID:368150,Continent:"South America",Country:"Colombia"},
  {ID:59,CountryCode:"DK",Location:"Denmark",WOEID:23424796,Continent:"Europe",Country:"Denmark"},
  {ID:60,CountryCode:"DO",Location:"Dominican Republic",WOEID:23424800,Continent:"North America",Country:"Dominican Republic"},
  {ID:61,CountryCode:"DO",Location:"Santo Domingo",WOEID:76456,Continent:"North America",Country:"Dominican Republic"},
  {ID:62,CountryCode:"EC",Location:"Ecuador",WOEID:23424801,Continent:"South America",Country:"Ecuador"},
  {ID:63,CountryCode:"EC",Location:"Guayaquil",WOEID:375733,Continent:"South America",Country:"Ecuador"},
  {ID:64,CountryCode:"EC",Location:"Quito",WOEID:375732,Continent:"South America",Country:"Ecuador"},
  {ID:65,CountryCode:"EG",Location:"Alexandria",WOEID:1522006,Continent:"Africa",Country:"Egypt"},
  {ID:66,CountryCode:"EG",Location:"Cairo",WOEID:1521894,Continent:"Africa",Country:"Egypt"},
  {ID:67,CountryCode:"EG",Location:"Egypt",WOEID:23424802,Continent:"Africa",Country:"Egypt"},
  {ID:68,CountryCode:"EG",Location:"Giza",WOEID:1521643,Continent:"Africa",Country:"Egypt"},
  {ID:69,CountryCode:"FR",Location:"Bordeaux",WOEID:580778,Continent:"Europe",Country:"France"},
  {ID:70,CountryCode:"FR",Location:"France",WOEID:23424819,Continent:"Europe",Country:"France"},
  {ID:71,CountryCode:"FR",Location:"Lille",WOEID:608105,Continent:"Europe",Country:"France"},
  {ID:72,CountryCode:"FR",Location:"Lyon",WOEID:609125,Continent:"Europe",Country:"France"},
  {ID:73,CountryCode:"FR",Location:"Marseille",WOEID:610264,Continent:"Europe",Country:"France"},
  {ID:74,CountryCode:"FR",Location:"Montpellier",WOEID:612977,Continent:"Europe",Country:"France"},
  {ID:75,CountryCode:"FR",Location:"Nantes",WOEID:613858,Continent:"Europe",Country:"France"},
  {ID:76,CountryCode:"FR",Location:"Paris",WOEID:615702,Continent:"Europe",Country:"France"},
  {ID:77,CountryCode:"FR",Location:"Rennes",WOEID:619163,Continent:"Europe",Country:"France"},
  {ID:78,CountryCode:"FR",Location:"Strasbourg",WOEID:627791,Continent:"Europe",Country:"France"},
  {ID:79,CountryCode:"FR",Location:"Toulouse",WOEID:628886,Continent:"Europe",Country:"France"},
  {ID:80,CountryCode:"DE",Location:"Berlin",WOEID:638242,Continent:"Europe",Country:"Germany"},
  {ID:81,CountryCode:"DE",Location:"Bremen",WOEID:641142,Continent:"Europe",Country:"Germany"},
  {ID:82,CountryCode:"DE",Location:"Cologne",WOEID:667931,Continent:"Europe",Country:"Germany"},
  {ID:83,CountryCode:"DE",Location:"Dortmund",WOEID:645458,Continent:"Europe",Country:"Germany"},
  {ID:84,CountryCode:"DE",Location:"Dresden",WOEID:645686,Continent:"Europe",Country:"Germany"},
  {ID:85,CountryCode:"DE",Location:"Dusseldorf",WOEID:646099,Continent:"Europe",Country:"Germany"},
  {ID:86,CountryCode:"DE",Location:"Essen",WOEID:648820,Continent:"Europe",Country:"Germany"},
  {ID:87,CountryCode:"DE",Location:"Frankfurt",WOEID:650272,Continent:"Europe",Country:"Germany"},
  {ID:88,CountryCode:"DE",Location:"Germany",WOEID:23424829,Continent:"Europe",Country:"Germany"},
  {ID:89,CountryCode:"DE",Location:"Hamburg",WOEID:656958,Continent:"Europe",Country:"Germany"},
  {ID:90,CountryCode:"DE",Location:"Leipzig",WOEID:671072,Continent:"Europe",Country:"Germany"},
  {ID:91,CountryCode:"DE",Location:"Munich",WOEID:676757,Continent:"Europe",Country:"Germany"},
  {ID:92,CountryCode:"DE",Location:"Stuttgart",WOEID:698064,Continent:"Europe",Country:"Germany"},
  {ID:93,CountryCode:"GH",Location:"Accra",WOEID:1326075,Continent:"Africa",Country:"Ghana"},
  {ID:94,CountryCode:"GH",Location:"Ghana",WOEID:23424824,Continent:"Africa",Country:"Ghana"},
  {ID:95,CountryCode:"GH",Location:"Kumasi",WOEID:1330595,Continent:"Africa",Country:"Ghana"},
  {ID:96,CountryCode:"GR",Location:"Athens",WOEID:946738,Continent:"Europe",Country:"Greece"},
  {ID:97,CountryCode:"GR",Location:"Greece",WOEID:23424833,Continent:"Europe",Country:"Greece"},
  {ID:98,CountryCode:"GR",Location:"Thessaloniki",WOEID:963291,Continent:"Europe",Country:"Greece"},
  {ID:99,CountryCode:"GT",Location:"Guatemala",WOEID:23424834,Continent:"North America",Country:"Guatemala"},
  {ID:100,CountryCode:"GT",Location:"Guatemala City",WOEID:83123,Continent:"North America",Country:"Guatemala"},
  {ID:101,CountryCode:"IN",Location:"Ahmedabad",WOEID:2295402,Continent:"Asia",Country:"India"},
  {ID:102,CountryCode:"IN",Location:"Amritsar",WOEID:2295388,Continent:"Asia",Country:"India"},
  {ID:103,CountryCode:"IN",Location:"Bangalore",WOEID:2295420,Continent:"Asia",Country:"India"},
  {ID:104,CountryCode:"IN",Location:"Bhopal",WOEID:2295407,Continent:"Asia",Country:"India"},
  {ID:105,CountryCode:"IN",Location:"Chennai",WOEID:2295424,Continent:"Asia",Country:"India"},
  {ID:106,CountryCode:"IN",Location:"Delhi",WOEID:20070458,Continent:"Asia",Country:"India"},
  {ID:107,CountryCode:"IN",Location:"Hyderabad",WOEID:2295414,Continent:"Asia",Country:"India"},
  {ID:108,CountryCode:"IN",Location:"India",WOEID:23424848,Continent:"Asia",Country:"India"},
  {ID:109,CountryCode:"IN",Location:"Indore",WOEID:2295408,Continent:"Asia",Country:"India"},
  {ID:110,CountryCode:"IN",Location:"Jaipur",WOEID:2295401,Continent:"Asia",Country:"India"},
  {ID:111,CountryCode:"IN",Location:"Kanpur",WOEID:2295378,Continent:"Asia",Country:"India"},
  {ID:112,CountryCode:"IN",Location:"Kolkata",WOEID:2295386,Continent:"Asia",Country:"India"},
  {ID:113,CountryCode:"IN",Location:"Lucknow",WOEID:2295377,Continent:"Asia",Country:"India"},
  {ID:114,CountryCode:"IN",Location:"Mumbai",WOEID:2295411,Continent:"Asia",Country:"India"},
  {ID:115,CountryCode:"IN",Location:"Nagpur",WOEID:2282863,Continent:"Asia",Country:"India"},
  {ID:116,CountryCode:"IN",Location:"Patna",WOEID:2295381,Continent:"Asia",Country:"India"},
  {ID:117,CountryCode:"IN",Location:"Pune",WOEID:2295412,Continent:"Asia",Country:"India"},
  {ID:118,CountryCode:"IN",Location:"Rajkot",WOEID:2295404,Continent:"Asia",Country:"India"},
  {ID:119,CountryCode:"IN",Location:"Ranchi",WOEID:2295383,Continent:"Asia",Country:"India"},
  {ID:120,CountryCode:"IN",Location:"Srinagar",WOEID:2295387,Continent:"Asia",Country:"India"},
  {ID:121,CountryCode:"IN",Location:"Surat",WOEID:2295405,Continent:"Asia",Country:"India"},
  {ID:122,CountryCode:"IN",Location:"Thane",WOEID:2295410,Continent:"Asia",Country:"India"},
  {ID:123,CountryCode:"ID",Location:"Bandung",WOEID:1047180,Continent:"Asia",Country:"Indonesia"},
  {ID:124,CountryCode:"ID",Location:"Bekasi",WOEID:1030077,Continent:"Asia",Country:"Indonesia"},
  {ID:125,CountryCode:"ID",Location:"Depok",WOEID:1032539,Continent:"Asia",Country:"Indonesia"},
  {ID:126,CountryCode:"ID",Location:"Indonesia",WOEID:23424846,Continent:"Asia",Country:"Indonesia"},
  {ID:127,CountryCode:"ID",Location:"Jakarta",WOEID:1047378,Continent:"Asia",Country:"Indonesia"},
  {ID:128,CountryCode:"ID",Location:"Makassar",WOEID:1046138,Continent:"Asia",Country:"Indonesia"},
  {ID:129,CountryCode:"ID",Location:"Medan",WOEID:1047908,Continent:"Asia",Country:"Indonesia"},
  {ID:130,CountryCode:"ID",Location:"Palembang",WOEID:1048059,Continent:"Asia",Country:"Indonesia"},
  {ID:131,CountryCode:"ID",Location:"Pekanbaru",WOEID:1040779,Continent:"Asia",Country:"Indonesia"},
  {ID:132,CountryCode:"ID",Location:"Semarang",WOEID:1048324,Continent:"Asia",Country:"Indonesia"},
  {ID:133,CountryCode:"ID",Location:"Surabaya",WOEID:1044316,Continent:"Asia",Country:"Indonesia"},
  {ID:134,CountryCode:"ID",Location:"Tangerang",WOEID:1048536,Continent:"Asia",Country:"Indonesia"},
  {ID:135,CountryCode:"IE",Location:"Cork",WOEID:560472,Continent:"Europe",Country:"Ireland"},
  {ID:136,CountryCode:"IE",Location:"Dublin",WOEID:560743,Continent:"Europe",Country:"Ireland"},
  {ID:137,CountryCode:"IE",Location:"Galway",WOEID:560912,Continent:"Europe",Country:"Ireland"},
  {ID:138,CountryCode:"IE",Location:"Ireland",WOEID:23424803,Continent:"Europe",Country:"Ireland"},
  {ID:139,CountryCode:"IL",Location:"Haifa",WOEID:1967449,Continent:"Asia",Country:"Israel"},
  {ID:140,CountryCode:"IL",Location:"Israel",WOEID:23424852,Continent:"Asia",Country:"Israel"},
  {ID:141,CountryCode:"IL",Location:"Jerusalem",WOEID:1968222,Continent:"Asia",Country:"Israel"},
  {ID:142,CountryCode:"IL",Location:"Tel Aviv",WOEID:1968212,Continent:"Asia",Country:"Israel"},
  {ID:143,CountryCode:"IT",Location:"Bologna",WOEID:711080,Continent:"Europe",Country:"Italy"},
  {ID:144,CountryCode:"IT",Location:"Genoa",WOEID:716085,Continent:"Europe",Country:"Italy"},
  {ID:145,CountryCode:"IT",Location:"Italy",WOEID:23424853,Continent:"Europe",Country:"Italy"},
  {ID:146,CountryCode:"IT",Location:"Milan",WOEID:718345,Continent:"Europe",Country:"Italy"},
  {ID:147,CountryCode:"IT",Location:"Naples",WOEID:719258,Continent:"Europe",Country:"Italy"},
  {ID:148,CountryCode:"IT",Location:"Palermo",WOEID:719846,Continent:"Europe",Country:"Italy"},
  {ID:149,CountryCode:"IT",Location:"Rome",WOEID:721943,Continent:"Europe",Country:"Italy"},
  {ID:150,CountryCode:"IT",Location:"Turin",WOEID:725003,Continent:"Europe",Country:"Italy"},
  {ID:151,CountryCode:"JP",Location:"Chiba",WOEID:1117034,Continent:"Asia",Country:"Japan"},
  {ID:152,CountryCode:"JP",Location:"Fukuoka",WOEID:1117099,Continent:"Asia",Country:"Japan"},
  {ID:153,CountryCode:"JP",Location:"Hamamatsu",WOEID:1117155,Continent:"Asia",Country:"Japan"},
  {ID:154,CountryCode:"JP",Location:"Hiroshima",WOEID:1117227,Continent:"Asia",Country:"Japan"},
  {ID:155,CountryCode:"JP",Location:"Japan",WOEID:23424856,Continent:"Asia",Country:"Japan"},
  {ID:156,CountryCode:"JP",Location:"Kawasaki",WOEID:1117502,Continent:"Asia",Country:"Japan"},
  {ID:157,CountryCode:"JP",Location:"Kitakyushu",WOEID:1110809,Continent:"Asia",Country:"Japan"},
  {ID:158,CountryCode:"JP",Location:"Kobe",WOEID:1117545,Continent:"Asia",Country:"Japan"},
  {ID:159,CountryCode:"JP",Location:"Kumamoto",WOEID:1117605,Continent:"Asia",Country:"Japan"},
  {ID:160,CountryCode:"JP",Location:"Kyoto",WOEID:15015372,Continent:"Asia",Country:"Japan"},
  {ID:161,CountryCode:"JP",Location:"Nagoya",WOEID:1117817,Continent:"Asia",Country:"Japan"},
  {ID:162,CountryCode:"JP",Location:"Niigata",WOEID:1117881,Continent:"Asia",Country:"Japan"},
  {ID:163,CountryCode:"JP",Location:"Okayama",WOEID:90036018,Continent:"Asia",Country:"Japan"},
  {ID:164,CountryCode:"JP",Location:"Okinawa",WOEID:2345896,Continent:"Asia",Country:"Japan"},
  {ID:165,CountryCode:"JP",Location:"Osaka",WOEID:15015370,Continent:"Asia",Country:"Japan"},
  {ID:166,CountryCode:"JP",Location:"Sagamihara",WOEID:1118072,Continent:"Asia",Country:"Japan"},
  {ID:167,CountryCode:"JP",Location:"Saitama",WOEID:1116753,Continent:"Asia",Country:"Japan"},
  {ID:168,CountryCode:"JP",Location:"Sapporo",WOEID:1118108,Continent:"Asia",Country:"Japan"},
  {ID:169,CountryCode:"JP",Location:"Sendai",WOEID:1118129,Continent:"Asia",Country:"Japan"},
  {ID:170,CountryCode:"JP",Location:"Takamatsu",WOEID:1118285,Continent:"Asia",Country:"Japan"},
  {ID:171,CountryCode:"JP",Location:"Tokyo",WOEID:1118370,Continent:"Asia",Country:"Japan"},
  {ID:172,CountryCode:"JP",Location:"Yokohama",WOEID:1118550,Continent:"Asia",Country:"Japan"},
  {ID:173,CountryCode:"JO",Location:"Amman",WOEID:1968902,Continent:"Asia",Country:"Jordan"},
  {ID:174,CountryCode:"JO",Location:"Jordan",WOEID:23424860,Continent:"Asia",Country:"Jordan"},
  {ID:175,CountryCode:"KE",Location:"Kenya",WOEID:23424863,Continent:"Africa",Country:"Kenya"},
  {ID:176,CountryCode:"KE",Location:"Mombasa",WOEID:1528335,Continent:"Africa",Country:"Kenya"},
  {ID:177,CountryCode:"KE",Location:"Nairobi",WOEID:1528488,Continent:"Africa",Country:"Kenya"},
  {ID:178,CountryCode:"KW",Location:"Kuwait",WOEID:23424870,Continent:"Asia",Country:"Kuwait"},
  {ID:179,CountryCode:"LV",Location:"Latvia",WOEID:23424874,Continent:"Europe",Country:"Latvia"},
  {ID:180,CountryCode:"LV",Location:"Riga",WOEID:854823,Continent:"Europe",Country:"Latvia"},
  {ID:181,CountryCode:"LB",Location:"Lebanon",WOEID:23424873,Continent:"Asia",Country:"Lebanon"},
  {ID:182,CountryCode:"MY",Location:"Hulu Langat",WOEID:56013645,Continent:"Asia",Country:"Malaysia"},
  {ID:183,CountryCode:"MY",Location:"Ipoh",WOEID:1154679,Continent:"Asia",Country:"Malaysia"},
  {ID:184,CountryCode:"MY",Location:"Johor Bahru",WOEID:1154698,Continent:"Asia",Country:"Malaysia"},
  {ID:185,CountryCode:"MY",Location:"Kajang",WOEID:1141268,Continent:"Asia",Country:"Malaysia"},
  {ID:186,CountryCode:"MY",Location:"Klang",WOEID:1154726,Continent:"Asia",Country:"Malaysia"},
  {ID:187,CountryCode:"MY",Location:"Kuala Lumpur",WOEID:1154781,Continent:"Asia",Country:"Malaysia"},
  {ID:188,CountryCode:"MY",Location:"Malaysia",WOEID:23424901,Continent:"Asia",Country:"Malaysia"},
  {ID:189,CountryCode:"MY",Location:"Petaling",WOEID:56013632,Continent:"Asia",Country:"Malaysia"},
  {ID:190,CountryCode:"MX",Location:"Acapulco",WOEID:110978,Continent:"North America",Country:"Mexico"},
  {ID:191,CountryCode:"MX",Location:"Aguascalientes",WOEID:111579,Continent:"North America",Country:"Mexico"},
  {ID:192,CountryCode:"MX",Location:"Chihuahua",WOEID:115958,Continent:"North America",Country:"Mexico"},
  {ID:193,CountryCode:"MX",Location:"Ciudad Juarez",WOEID:116556,Continent:"North America",Country:"Mexico"},
  {ID:194,CountryCode:"MX",Location:"Culiacán",WOEID:117994,Continent:"North America",Country:"Mexico"},
  {ID:195,CountryCode:"MX",Location:"Ecatepec de Morelos",WOEID:118466,Continent:"North America",Country:"Mexico"},
  {ID:196,CountryCode:"MX",Location:"Guadalajara",WOEID:124162,Continent:"North America",Country:"Mexico"},
  {ID:197,CountryCode:"MX",Location:"Hermosillo",WOEID:124785,Continent:"North America",Country:"Mexico"},
  {ID:198,CountryCode:"MX",Location:"León",WOEID:131068,Continent:"North America",Country:"Mexico"},
  {ID:199,CountryCode:"MX",Location:"Mérida",WOEID:133327,Continent:"North America",Country:"Mexico"},
  {ID:200,CountryCode:"MX",Location:"Mexicali",WOEID:133475,Continent:"North America",Country:"Mexico"},
  {ID:201,CountryCode:"MX",Location:"Mexico",WOEID:23424900,Continent:"North America",Country:"Mexico"},
  {ID:202,CountryCode:"MX",Location:"Mexico City",WOEID:116545,Continent:"North America",Country:"Mexico"},
  {ID:203,CountryCode:"MX",Location:"Monterrey",WOEID:134047,Continent:"North America",Country:"Mexico"},
  {ID:204,CountryCode:"MX",Location:"Morelia",WOEID:134091,Continent:"North America",Country:"Mexico"},
  {ID:205,CountryCode:"MX",Location:"Naucalpan de Juárez",WOEID:134395,Continent:"North America",Country:"Mexico"},
  {ID:206,CountryCode:"MX",Location:"Nezahualcóyotl",WOEID:116564,Continent:"North America",Country:"Mexico"},
  {ID:207,CountryCode:"MX",Location:"Puebla",WOEID:137612,Continent:"North America",Country:"Mexico"},
  {ID:208,CountryCode:"MX",Location:"Querétaro",WOEID:138045,Continent:"North America",Country:"Mexico"},
  {ID:209,CountryCode:"MX",Location:"Saltillo",WOEID:141272,Continent:"North America",Country:"Mexico"},
  {ID:210,CountryCode:"MX",Location:"San Luis Potosí",WOEID:144265,Continent:"North America",Country:"Mexico"},
  {ID:211,CountryCode:"MX",Location:"Tijuana",WOEID:149361,Continent:"North America",Country:"Mexico"},
  {ID:212,CountryCode:"MX",Location:"Toluca",WOEID:149769,Continent:"North America",Country:"Mexico"},
  {ID:213,CountryCode:"MX",Location:"Zapopan",WOEID:151582,Continent:"North America",Country:"Mexico"},
  {ID:214,CountryCode:"NL",Location:"Amsterdam",WOEID:727232,Continent:"Europe",Country:"Netherlands"},
  {ID:215,CountryCode:"NL",Location:"Den Haag",WOEID:726874,Continent:"Europe",Country:"Netherlands"},
  {ID:216,CountryCode:"NL",Location:"Netherlands",WOEID:23424909,Continent:"Europe",Country:"Netherlands"},
  {ID:217,CountryCode:"NL",Location:"Rotterdam",WOEID:733075,Continent:"Europe",Country:"Netherlands"},
  {ID:218,CountryCode:"NL",Location:"Utrecht",WOEID:734047,Continent:"Europe",Country:"Netherlands"},
  {ID:219,CountryCode:"NZ",Location:"Auckland",WOEID:2348079,Continent:"Australia",Country:"New Zealand"},
  {ID:220,CountryCode:"NZ",Location:"New Zealand",WOEID:23424916,Continent:"Australia",Country:"New Zealand"},
  {ID:221,CountryCode:"NG",Location:"Benin City",WOEID:1387660,Continent:"Africa",Country:"Nigeria"},
  {ID:222,CountryCode:"NG",Location:"Ibadan",WOEID:1393672,Continent:"Africa",Country:"Nigeria"},
  {ID:223,CountryCode:"NG",Location:"Kaduna",WOEID:1396439,Continent:"Africa",Country:"Nigeria"},
  {ID:224,CountryCode:"NG",Location:"Kano",WOEID:1396803,Continent:"Africa",Country:"Nigeria"},
  {ID:225,CountryCode:"NG",Location:"Lagos",WOEID:1398823,Continent:"Africa",Country:"Nigeria"},
  {ID:226,CountryCode:"NG",Location:"Nigeria",WOEID:23424908,Continent:"Africa",Country:"Nigeria"},
  {ID:227,CountryCode:"NG",Location:"Port Harcourt",WOEID:1404447,Continent:"Africa",Country:"Nigeria"},
  {ID:228,CountryCode:"NO",Location:"Bergen",WOEID:857105,Continent:"Europe",Country:"Norway"},
  {ID:229,CountryCode:"NO",Location:"Norway",WOEID:23424910,Continent:"Europe",Country:"Norway"},
  {ID:230,CountryCode:"NO",Location:"Oslo",WOEID:862592,Continent:"Europe",Country:"Norway"},
  {ID:231,CountryCode:"OM",Location:"Muscat",WOEID:2268284,Continent:"Asia",Country:"Oman"},
  {ID:232,CountryCode:"OM",Location:"Oman",WOEID:23424898,Continent:"Asia",Country:"Oman"},
  {ID:233,CountryCode:"PK",Location:"Faisalabad",WOEID:2211574,Continent:"Asia",Country:"Pakistan"},
  {ID:234,CountryCode:"PK",Location:"Karachi",WOEID:2211096,Continent:"Asia",Country:"Pakistan"},
  {ID:235,CountryCode:"PK",Location:"Lahore",WOEID:2211177,Continent:"Asia",Country:"Pakistan"},
  {ID:236,CountryCode:"PK",Location:"Multan",WOEID:2211269,Continent:"Asia",Country:"Pakistan"},
  {ID:237,CountryCode:"PK",Location:"Pakistan",WOEID:23424922,Continent:"Asia",Country:"Pakistan"},
  {ID:238,CountryCode:"PK",Location:"Rawalpindi",WOEID:2211387,Continent:"Asia",Country:"Pakistan"},
  {ID:239,CountryCode:"PA",Location:"Panama",WOEID:23424924,Continent:"North America",Country:"Panama"},
  {ID:240,CountryCode:"PE",Location:"Lima",WOEID:418440,Continent:"South America",Country:"Peru"},
  {ID:241,CountryCode:"PE",Location:"Peru",WOEID:23424919,Continent:"South America",Country:"Peru"},
  {ID:242,CountryCode:"PH",Location:"Antipolo",WOEID:1198785,Continent:"Asia",Country:"Philippines"},
  {ID:243,CountryCode:"PH",Location:"Cagayan de Oro",WOEID:1199002,Continent:"Asia",Country:"Philippines"},
  {ID:244,CountryCode:"PH",Location:"Calocan",WOEID:1167715,Continent:"Asia",Country:"Philippines"},
  {ID:245,CountryCode:"PH",Location:"Cebu City",WOEID:1199079,Continent:"Asia",Country:"Philippines"},
  {ID:246,CountryCode:"PH",Location:"Davao City",WOEID:1199136,Continent:"Asia",Country:"Philippines"},
  {ID:247,CountryCode:"PH",Location:"Makati",WOEID:1180689,Continent:"Asia",Country:"Philippines"},
  {ID:248,CountryCode:"PH",Location:"Manila",WOEID:1199477,Continent:"Asia",Country:"Philippines"},
  {ID:249,CountryCode:"PH",Location:"Pasig",WOEID:1187115,Continent:"Asia",Country:"Philippines"},
  {ID:250,CountryCode:"PH",Location:"Philippines",WOEID:23424934,Continent:"Asia",Country:"Philippines"},
  {ID:251,CountryCode:"PH",Location:"Quezon City",WOEID:1199682,Continent:"Asia",Country:"Philippines"},
  {ID:252,CountryCode:"PH",Location:"Taguig",WOEID:1195098,Continent:"Asia",Country:"Philippines"},
  {ID:253,CountryCode:"PH",Location:"Zamboanga City",WOEID:1199980,Continent:"Asia",Country:"Philippines"},
  {ID:254,CountryCode:"PL",Location:"Gdańsk",WOEID:493417,Continent:"Europe",Country:"Poland"},
  {ID:255,CountryCode:"PL",Location:"Kraków",WOEID:502075,Continent:"Europe",Country:"Poland"},
  {ID:256,CountryCode:"PL",Location:"Lodz",WOEID:505120,Continent:"Europe",Country:"Poland"},
  {ID:257,CountryCode:"PL",Location:"Poland",WOEID:23424923,Continent:"Europe",Country:"Poland"},
  {ID:258,CountryCode:"PL",Location:"Poznań",WOEID:514048,Continent:"Europe",Country:"Poland"},
  {ID:259,CountryCode:"PL",Location:"Warsaw",WOEID:523920,Continent:"Europe",Country:"Poland"},
  {ID:260,CountryCode:"PL",Location:"Wroclaw",WOEID:526363,Continent:"Europe",Country:"Poland"},
  {ID:261,CountryCode:"PT",Location:"Portugal",WOEID:23424925,Continent:"Europe",Country:"Portugal"},
  {ID:262,CountryCode:"PR",Location:"Puerto Rico",WOEID:23424935,Continent:"North America",Country:"Puerto Rico"},
  {ID:263,CountryCode:"QA",Location:"Qatar",WOEID:23424930,Continent:"Asia",Country:"Qatar"},
  {ID:264,CountryCode:"RU",Location:"Chelyabinsk",WOEID:1997422,Continent:"Asia",Country:"Russian Federation"},
  {ID:265,CountryCode:"RU",Location:"Irkutsk",WOEID:2121040,Continent:"Asia",Country:"Russian Federation"},
  {ID:266,CountryCode:"RU",Location:"Kazan",WOEID:2121267,Continent:"Asia",Country:"Russian Federation"},
  {ID:267,CountryCode:"RU",Location:"Khabarovsk",WOEID:2018708,Continent:"Asia",Country:"Russian Federation"},
  {ID:268,CountryCode:"RU",Location:"Krasnodar",WOEID:2028717,Continent:"Asia",Country:"Russian Federation"},
  {ID:269,CountryCode:"RU",Location:"Krasnoyarsk",WOEID:2029043,Continent:"Asia",Country:"Russian Federation"},
  {ID:270,CountryCode:"RU",Location:"Moscow",WOEID:2122265,Continent:"Asia",Country:"Russian Federation"},
  {ID:271,CountryCode:"RU",Location:"Nizhny Novgorod",WOEID:2122471,Continent:"Asia",Country:"Russian Federation"},
  {ID:272,CountryCode:"RU",Location:"Novosibirsk",WOEID:2122541,Continent:"Asia",Country:"Russian Federation"},
  {ID:273,CountryCode:"RU",Location:"Omsk",WOEID:2122641,Continent:"Asia",Country:"Russian Federation"},
  {ID:274,CountryCode:"RU",Location:"Perm",WOEID:2122814,Continent:"Asia",Country:"Russian Federation"},
  {ID:275,CountryCode:"RU",Location:"Rostov-on-Don",WOEID:2123177,Continent:"Asia",Country:"Russian Federation"},
  {ID:276,CountryCode:"RU",Location:"Russia",WOEID:23424936,Continent:"Asia",Country:"Russian Federation"},
  {ID:277,CountryCode:"RU",Location:"Saint Petersburg",WOEID:2123260,Continent:"Asia",Country:"Russian Federation"},
  {ID:278,CountryCode:"RU",Location:"Samara",WOEID:2077746,Continent:"Asia",Country:"Russian Federation"},
  {ID:279,CountryCode:"RU",Location:"Ufa",WOEID:2124045,Continent:"Asia",Country:"Russian Federation"},
  {ID:280,CountryCode:"RU",Location:"Vladivostok",WOEID:2124288,Continent:"Asia",Country:"Russian Federation"},
  {ID:281,CountryCode:"RU",Location:"Volgograd",WOEID:2124298,Continent:"Asia",Country:"Russian Federation"},
  {ID:282,CountryCode:"RU",Location:"Voronezh",WOEID:2108210,Continent:"Asia",Country:"Russian Federation"},
  {ID:283,CountryCode:"RU",Location:"Yekaterinburg",WOEID:2112237,Continent:"Asia",Country:"Russian Federation"},
  {ID:284,CountryCode:"SA",Location:"Ahsa",WOEID:56120136,Continent:"Asia",Country:"Saudi Arabia"},
  {ID:285,CountryCode:"SA",Location:"Dammam",WOEID:1939574,Continent:"Asia",Country:"Saudi Arabia"},
  {ID:286,CountryCode:"SA",Location:"Jeddah",WOEID:1939873,Continent:"Asia",Country:"Saudi Arabia"},
  {ID:287,CountryCode:"SA",Location:"Mecca",WOEID:1939897,Continent:"Asia",Country:"Saudi Arabia"},
  {ID:288,CountryCode:"SA",Location:"Medina",WOEID:1937801,Continent:"Asia",Country:"Saudi Arabia"},
  {ID:289,CountryCode:"SA",Location:"Riyadh",WOEID:1939753,Continent:"Asia",Country:"Saudi Arabia"},
  {ID:290,CountryCode:"SA",Location:"Saudi Arabia",WOEID:23424938,Continent:"Asia",Country:"Saudi Arabia"},
  {ID:291,CountryCode:"SG",Location:"Singapore",WOEID:1062617,Continent:"Asia",Country:"Singapore"},
  {ID:292,CountryCode:"SG",Location:"Singapore",WOEID:23424948,Continent:"Asia",Country:"Singapore"},
  {ID:293,CountryCode:"ZA",Location:"Cape Town",WOEID:1591691,Continent:"Africa",Country:"South Africa"},
  {ID:294,CountryCode:"ZA",Location:"Durban",WOEID:1580913,Continent:"Africa",Country:"South Africa"},
  {ID:295,CountryCode:"ZA",Location:"Johannesburg",WOEID:1582504,Continent:"Africa",Country:"South Africa"},
  {ID:296,CountryCode:"ZA",Location:"Port Elizabeth",WOEID:1586614,Continent:"Africa",Country:"South Africa"},
  {ID:297,CountryCode:"ZA",Location:"Pretoria",WOEID:1586638,Continent:"Africa",Country:"South Africa"},
  {ID:298,CountryCode:"ZA",Location:"South Africa",WOEID:23424942,Continent:"Africa",Country:"South Africa"},
  {ID:299,CountryCode:"ZA",Location:"Soweto",WOEID:1587677,Continent:"Africa",Country:"South Africa"},
  {ID:300,CountryCode:"KR",Location:"Ansan",WOEID:1132444,Continent:"Asia",Country:"South Korea"},
  {ID:301,CountryCode:"KR",Location:"Bucheon",WOEID:1132445,Continent:"Asia",Country:"South Korea"},
  {ID:302,CountryCode:"KR",Location:"Busan",WOEID:1132447,Continent:"Asia",Country:"South Korea"},
  {ID:303,CountryCode:"KR",Location:"Changwon",WOEID:1132449,Continent:"Asia",Country:"South Korea"},
  {ID:304,CountryCode:"KR",Location:"Daegu",WOEID:1132466,Continent:"Asia",Country:"South Korea"},
  {ID:305,CountryCode:"KR",Location:"Daejeon",WOEID:2345975,Continent:"Asia",Country:"South Korea"},
  {ID:306,CountryCode:"KR",Location:"Goyang",WOEID:1130853,Continent:"Asia",Country:"South Korea"},
  {ID:307,CountryCode:"KR",Location:"Gwangju",WOEID:1132481,Continent:"Asia",Country:"South Korea"},
  {ID:308,CountryCode:"KR",Location:"Incheon",WOEID:1132496,Continent:"Asia",Country:"South Korea"},
  {ID:309,CountryCode:"KR",Location:"Korea",WOEID:23424868,Continent:"Asia",Country:"South Korea"},
  {ID:310,CountryCode:"KR",Location:"Seongnam",WOEID:1132559,Continent:"Asia",Country:"South Korea"},
  {ID:311,CountryCode:"KR",Location:"Seoul",WOEID:1132599,Continent:"Asia",Country:"South Korea"},
  {ID:312,CountryCode:"KR",Location:"Suwon",WOEID:1132567,Continent:"Asia",Country:"South Korea"},
  {ID:313,CountryCode:"KR",Location:"Ulsan",WOEID:1132578,Continent:"Asia",Country:"South Korea"},
  {ID:314,CountryCode:"KR",Location:"Yongin",WOEID:1132094,Continent:"Asia",Country:"South Korea"},
  {ID:315,CountryCode:"ES",Location:"Barcelona",WOEID:753692,Continent:"Europe",Country:"Spain"},
  {ID:316,CountryCode:"ES",Location:"Bilbao",WOEID:754542,Continent:"Europe",Country:"Spain"},
  {ID:317,CountryCode:"ES",Location:"Las Palmas",WOEID:764814,Continent:"Europe",Country:"Spain"},
  {ID:318,CountryCode:"ES",Location:"Madrid",WOEID:766273,Continent:"Europe",Country:"Spain"},
  {ID:319,CountryCode:"ES",Location:"Malaga",WOEID:766356,Continent:"Europe",Country:"Spain"},
  {ID:320,CountryCode:"ES",Location:"Murcia",WOEID:768026,Continent:"Europe",Country:"Spain"},
  {ID:321,CountryCode:"ES",Location:"Palma",WOEID:769293,Continent:"Europe",Country:"Spain"},
  {ID:322,CountryCode:"ES",Location:"Seville",WOEID:774508,Continent:"Europe",Country:"Spain"},
  {ID:323,CountryCode:"ES",Location:"Spain",WOEID:23424950,Continent:"Europe",Country:"Spain"},
  {ID:324,CountryCode:"ES",Location:"Valencia",WOEID:776688,Continent:"Europe",Country:"Spain"},
  {ID:325,CountryCode:"ES",Location:"Zaragoza",WOEID:779063,Continent:"Europe",Country:"Spain"},
  {ID:326,CountryCode:"SE",Location:"Gothenburg",WOEID:890869,Continent:"Europe",Country:"Sweden"},
  {ID:327,CountryCode:"SE",Location:"Stockholm",WOEID:906057,Continent:"Europe",Country:"Sweden"},
  {ID:328,CountryCode:"SE",Location:"Sweden",WOEID:23424954,Continent:"Europe",Country:"Sweden"},
  {ID:329,CountryCode:"CH",Location:"Geneva",WOEID:782538,Continent:"Europe",Country:"Switzerland"},
  {ID:330,CountryCode:"CH",Location:"Lausanne",WOEID:783058,Continent:"Europe",Country:"Switzerland"},
  {ID:331,CountryCode:"CH",Location:"Switzerland",WOEID:23424957,Continent:"Europe",Country:"Switzerland"},
  {ID:332,CountryCode:"CH",Location:"Zurich",WOEID:784794,Continent:"Europe",Country:"Switzerland"},
  {ID:333,CountryCode:"TH",Location:"Bangkok",WOEID:1225448,Continent:"Asia",Country:"Thailand"},
  {ID:334,CountryCode:"TH",Location:"Thailand",WOEID:23424960,Continent:"Asia",Country:"Thailand"},
  {ID:335,CountryCode:"TR",Location:"Adana",WOEID:2343678,Continent:"Asia",Country:"Turkey"},
  {ID:336,CountryCode:"TR",Location:"Ankara",WOEID:2343732,Continent:"Asia",Country:"Turkey"},
  {ID:337,CountryCode:"TR",Location:"Antalya",WOEID:2343733,Continent:"Asia",Country:"Turkey"},
  {ID:338,CountryCode:"TR",Location:"Bursa",WOEID:2343843,Continent:"Asia",Country:"Turkey"},
  {ID:339,CountryCode:"TR",Location:"Diyarbakır",WOEID:2343932,Continent:"Asia",Country:"Turkey"},
  {ID:340,CountryCode:"TR",Location:"Eskişehir",WOEID:2343980,Continent:"Asia",Country:"Turkey"},
  {ID:341,CountryCode:"TR",Location:"Gaziantep",WOEID:2343999,Continent:"Asia",Country:"Turkey"},
  {ID:342,CountryCode:"TR",Location:"Istanbul",WOEID:2344116,Continent:"Asia",Country:"Turkey"},
  {ID:343,CountryCode:"TR",Location:"Izmir",WOEID:2344117,Continent:"Asia",Country:"Turkey"},
  {ID:344,CountryCode:"TR",Location:"Kayseri",WOEID:2344174,Continent:"Asia",Country:"Turkey"},
  {ID:345,CountryCode:"TR",Location:"Konya",WOEID:2344210,Continent:"Asia",Country:"Turkey"},
  {ID:346,CountryCode:"TR",Location:"Mersin",WOEID:2323778,Continent:"Asia",Country:"Turkey"},
  {ID:347,CountryCode:"TR",Location:"Turkey",WOEID:23424969,Continent:"Asia",Country:"Turkey"},
  {ID:348,CountryCode:"UA",Location:"Dnipropetrovsk",WOEID:918981,Continent:"Europe",Country:"Ukraine"},
  {ID:349,CountryCode:"UA",Location:"Donetsk",WOEID:919163,Continent:"Europe",Country:"Ukraine"},
  {ID:350,CountryCode:"UA",Location:"Kharkiv",WOEID:922137,Continent:"Europe",Country:"Ukraine"},
  {ID:351,CountryCode:"UA",Location:"Kyiv",WOEID:924938,Continent:"Europe",Country:"Ukraine"},
  {ID:352,CountryCode:"UA",Location:"Lviv",WOEID:924943,Continent:"Europe",Country:"Ukraine"},
  {ID:353,CountryCode:"UA",Location:"Odesa",WOEID:929398,Continent:"Europe",Country:"Ukraine"},
  {ID:354,CountryCode:"UA",Location:"Ukraine",WOEID:23424976,Continent:"Europe",Country:"Ukraine"},
  {ID:355,CountryCode:"UA",Location:"Zaporozhye",WOEID:939628,Continent:"Europe",Country:"Ukraine"},
  {ID:356,CountryCode:"AE",Location:"Abu Dhabi",WOEID:1940330,Continent:"Asia",Country:"United Arab Emirates"},
  {ID:357,CountryCode:"AE",Location:"Dubai",WOEID:1940345,Continent:"Asia",Country:"United Arab Emirates"},
  {ID:358,CountryCode:"AE",Location:"Sharjah",WOEID:1940119,Continent:"Asia",Country:"United Arab Emirates"},
  {ID:359,CountryCode:"AE",Location:"United Arab Emirates",WOEID:23424738,Continent:"Asia",Country:"United Arab Emirates"},
  {ID:360,CountryCode:"GB",Location:"Belfast",WOEID:44544,Continent:"Europe",Country:"United Kingdom"},
  {ID:361,CountryCode:"GB",Location:"Birmingham",WOEID:12723,Continent:"Europe",Country:"United Kingdom"},
  {ID:362,CountryCode:"GB",Location:"Blackpool",WOEID:12903,Continent:"Europe",Country:"United Kingdom"},
  {ID:363,CountryCode:"GB",Location:"Bournemouth",WOEID:13383,Continent:"Europe",Country:"United Kingdom"},
  {ID:364,CountryCode:"GB",Location:"Brighton",WOEID:13911,Continent:"Europe",Country:"United Kingdom"},
  {ID:365,CountryCode:"GB",Location:"Bristol",WOEID:13963,Continent:"Europe",Country:"United Kingdom"},
  {ID:366,CountryCode:"GB",Location:"Cardiff",WOEID:15127,Continent:"Europe",Country:"United Kingdom"},
  {ID:367,CountryCode:"GB",Location:"Coventry",WOEID:17044,Continent:"Europe",Country:"United Kingdom"},
  {ID:368,CountryCode:"GB",Location:"Derby",WOEID:18114,Continent:"Europe",Country:"United Kingdom"},
  {ID:369,CountryCode:"GB",Location:"Edinburgh",WOEID:19344,Continent:"Europe",Country:"United Kingdom"},
  {ID:370,CountryCode:"GB",Location:"Glasgow",WOEID:21125,Continent:"Europe",Country:"United Kingdom"},
  {ID:371,CountryCode:"GB",Location:"Hull",WOEID:25211,Continent:"Europe",Country:"United Kingdom"},
  {ID:372,CountryCode:"GB",Location:"Leeds",WOEID:26042,Continent:"Europe",Country:"United Kingdom"},
  {ID:373,CountryCode:"GB",Location:"Leicester",WOEID:26062,Continent:"Europe",Country:"United Kingdom"},
  {ID:374,CountryCode:"GB",Location:"Liverpool",WOEID:26734,Continent:"Europe",Country:"United Kingdom"},
  {ID:375,CountryCode:"GB",Location:"London",WOEID:44418,Continent:"Europe",Country:"United Kingdom"},
  {ID:376,CountryCode:"GB",Location:"Manchester",WOEID:28218,Continent:"Europe",Country:"United Kingdom"},
  {ID:377,CountryCode:"GB",Location:"Middlesbrough",WOEID:28869,Continent:"Europe",Country:"United Kingdom"},
  {ID:378,CountryCode:"GB",Location:"Newcastle",WOEID:30079,Continent:"Europe",Country:"United Kingdom"},
  {ID:379,CountryCode:"GB",Location:"Nottingham",WOEID:30720,Continent:"Europe",Country:"United Kingdom"},
  {ID:380,CountryCode:"GB",Location:"Plymouth",WOEID:32185,Continent:"Europe",Country:"United Kingdom"},
  {ID:381,CountryCode:"GB",Location:"Portsmouth",WOEID:32452,Continent:"Europe",Country:"United Kingdom"},
  {ID:382,CountryCode:"GB",Location:"Preston",WOEID:32566,Continent:"Europe",Country:"United Kingdom"},
  {ID:383,CountryCode:"GB",Location:"Sheffield",WOEID:34503,Continent:"Europe",Country:"United Kingdom"},
  {ID:384,CountryCode:"GB",Location:"Stoke-on-Trent",WOEID:36240,Continent:"Europe",Country:"United Kingdom"},
  {ID:385,CountryCode:"GB",Location:"Swansea",WOEID:36758,Continent:"Europe",Country:"United Kingdom"},
  {ID:386,CountryCode:"GB",Location:"United Kingdom",WOEID:23424975,Continent:"Europe",Country:"United Kingdom"},
  {ID:387,CountryCode:"US",Location:"Albuquerque",WOEID:2352824,Continent:"North America",Country:"United States of America"},
  {ID:388,CountryCode:"US",Location:"Atlanta",WOEID:2357024,Continent:"North America",Country:"United States of America"},
  {ID:389,CountryCode:"US",Location:"Austin",WOEID:2357536,Continent:"North America",Country:"United States of America"},
  {ID:390,CountryCode:"US",Location:"Baltimore",WOEID:2358820,Continent:"North America",Country:"United States of America"},
  {ID:391,CountryCode:"US",Location:"Baton Rouge",WOEID:2359991,Continent:"North America",Country:"United States of America"},
  {ID:392,CountryCode:"US",Location:"Birmingham",WOEID:2364559,Continent:"North America",Country:"United States of America"},
  {ID:393,CountryCode:"US",Location:"Boston",WOEID:2367105,Continent:"North America",Country:"United States of America"},
  {ID:394,CountryCode:"US",Location:"Charlotte",WOEID:2378426,Continent:"North America",Country:"United States of America"},
  {ID:395,CountryCode:"US",Location:"Chicago",WOEID:2379574,Continent:"North America",Country:"United States of America"},
  {ID:396,CountryCode:"US",Location:"Cincinnati",WOEID:2380358,Continent:"North America",Country:"United States of America"},
  {ID:397,CountryCode:"US",Location:"Cleveland",WOEID:2381475,Continent:"North America",Country:"United States of America"},
  {ID:398,CountryCode:"US",Location:"Colorado Springs",WOEID:2383489,Continent:"North America",Country:"United States of America"},
  {ID:399,CountryCode:"US",Location:"Columbus",WOEID:2383660,Continent:"North America",Country:"United States of America"},
  {ID:400,CountryCode:"US",Location:"Dallas-Ft. Worth",WOEID:2388929,Continent:"North America",Country:"United States of America"},
  {ID:401,CountryCode:"US",Location:"Denver",WOEID:2391279,Continent:"North America",Country:"United States of America"},
  {ID:402,CountryCode:"US",Location:"Detroit",WOEID:2391585,Continent:"North America",Country:"United States of America"},
  {ID:403,CountryCode:"US",Location:"El Paso",WOEID:2397816,Continent:"North America",Country:"United States of America"},
  {ID:404,CountryCode:"US",Location:"Fresno",WOEID:2407517,Continent:"North America",Country:"United States of America"},
  {ID:405,CountryCode:"US",Location:"Greensboro",WOEID:2414469,Continent:"North America",Country:"United States of America"},
  {ID:406,CountryCode:"US",Location:"Harrisburg",WOEID:2418046,Continent:"North America",Country:"United States of America"},
  {ID:407,CountryCode:"US",Location:"Honolulu",WOEID:2423945,Continent:"North America",Country:"United States of America"},
  {ID:408,CountryCode:"US",Location:"Houston",WOEID:2424766,Continent:"North America",Country:"United States of America"},
  {ID:409,CountryCode:"US",Location:"Indianapolis",WOEID:2427032,Continent:"North America",Country:"United States of America"},
  {ID:410,CountryCode:"US",Location:"Jackson",WOEID:2428184,Continent:"North America",Country:"United States of America"},
  {ID:411,CountryCode:"US",Location:"Jacksonville",WOEID:2428344,Continent:"North America",Country:"United States of America"},
  {ID:412,CountryCode:"US",Location:"Kansas City",WOEID:2430683,Continent:"North America",Country:"United States of America"},
  {ID:413,CountryCode:"US",Location:"Las Vegas",WOEID:2436704,Continent:"North America",Country:"United States of America"},
  {ID:414,CountryCode:"US",Location:"Long Beach",WOEID:2441472,Continent:"North America",Country:"United States of America"},
  {ID:415,CountryCode:"US",Location:"Los Angeles",WOEID:2442047,Continent:"North America",Country:"United States of America"},
  {ID:416,CountryCode:"US",Location:"Louisville",WOEID:2442327,Continent:"North America",Country:"United States of America"},
  {ID:417,CountryCode:"US",Location:"Memphis",WOEID:2449323,Continent:"North America",Country:"United States of America"},
  {ID:418,CountryCode:"US",Location:"Mesa",WOEID:2449808,Continent:"North America",Country:"United States of America"},
  {ID:419,CountryCode:"US",Location:"Miami",WOEID:2450022,Continent:"North America",Country:"United States of America"},
  {ID:420,CountryCode:"US",Location:"Milwaukee",WOEID:2451822,Continent:"North America",Country:"United States of America"},
  {ID:421,CountryCode:"US",Location:"Minneapolis",WOEID:2452078,Continent:"North America",Country:"United States of America"},
  {ID:422,CountryCode:"US",Location:"Nashville",WOEID:2457170,Continent:"North America",Country:"United States of America"},
  {ID:423,CountryCode:"US",Location:"New Haven",WOEID:2458410,Continent:"North America",Country:"United States of America"},
  {ID:424,CountryCode:"US",Location:"New Orleans",WOEID:2458833,Continent:"North America",Country:"United States of America"},
  {ID:425,CountryCode:"US",Location:"New York",WOEID:2459115,Continent:"North America",Country:"United States of America"},
  {ID:426,CountryCode:"US",Location:"Norfolk",WOEID:2460389,Continent:"North America",Country:"United States of America"},
  {ID:427,CountryCode:"US",Location:"Oklahoma City",WOEID:2464592,Continent:"North America",Country:"United States of America"},
  {ID:428,CountryCode:"US",Location:"Omaha",WOEID:2465512,Continent:"North America",Country:"United States of America"},
  {ID:429,CountryCode:"US",Location:"Orlando",WOEID:2466256,Continent:"North America",Country:"United States of America"},
  {ID:430,CountryCode:"US",Location:"Philadelphia",WOEID:2471217,Continent:"North America",Country:"United States of America"},
  {ID:431,CountryCode:"US",Location:"Phoenix",WOEID:2471390,Continent:"North America",Country:"United States of America"},
  {ID:432,CountryCode:"US",Location:"Pittsburgh",WOEID:2473224,Continent:"North America",Country:"United States of America"},
  {ID:433,CountryCode:"US",Location:"Portland",WOEID:2475687,Continent:"North America",Country:"United States of America"},
  {ID:434,CountryCode:"US",Location:"Providence",WOEID:2477058,Continent:"North America",Country:"United States of America"},
  {ID:435,CountryCode:"US",Location:"Raleigh",WOEID:2478307,Continent:"North America",Country:"United States of America"},
  {ID:436,CountryCode:"US",Location:"Richmond",WOEID:2480894,Continent:"North America",Country:"United States of America"},
  {ID:437,CountryCode:"US",Location:"Sacramento",WOEID:2486340,Continent:"North America",Country:"United States of America"},
  {ID:438,CountryCode:"US",Location:"Salt Lake City",WOEID:2487610,Continent:"North America",Country:"United States of America"},
  {ID:439,CountryCode:"US",Location:"San Antonio",WOEID:2487796,Continent:"North America",Country:"United States of America"},
  {ID:440,CountryCode:"US",Location:"San Diego",WOEID:2487889,Continent:"North America",Country:"United States of America"},
  {ID:441,CountryCode:"US",Location:"San Francisco",WOEID:2487956,Continent:"North America",Country:"United States of America"},
  {ID:442,CountryCode:"US",Location:"San Jose",WOEID:2488042,Continent:"North America",Country:"United States of America"},
  {ID:443,CountryCode:"US",Location:"Seattle",WOEID:2490383,Continent:"North America",Country:"United States of America"},
  {ID:444,CountryCode:"US",Location:"St. Louis",WOEID:2486982,Continent:"North America",Country:"United States of America"},
  {ID:445,CountryCode:"US",Location:"Tallahassee",WOEID:2503713,Continent:"North America",Country:"United States of America"},
  {ID:446,CountryCode:"US",Location:"Tampa",WOEID:2503863,Continent:"North America",Country:"United States of America"},
  {ID:447,CountryCode:"US",Location:"Tucson",WOEID:2508428,Continent:"North America",Country:"United States of America"},
  {ID:448,CountryCode:"US",Location:"United States",WOEID:23424977,Continent:"North America",Country:"United States of America"},
  {ID:449,CountryCode:"US",Location:"Virginia Beach",WOEID:2512636,Continent:"North America",Country:"United States of America"},
  {ID:450,CountryCode:"US",Location:"Washington",WOEID:2514815,Continent:"North America",Country:"United States of America"},
  {ID:451,CountryCode:"VE",Location:"Barcelona",WOEID:395273,Continent:"South America",Country:"Venezuela"},
  {ID:452,CountryCode:"VE",Location:"Barquisimeto",WOEID:468382,Continent:"South America",Country:"Venezuela"},
  {ID:453,CountryCode:"VE",Location:"Caracas",WOEID:395269,Continent:"South America",Country:"Venezuela"},
  {ID:454,CountryCode:"VE",Location:"Ciudad Guayana",WOEID:395275,Continent:"South America",Country:"Venezuela"},
  {ID:455,CountryCode:"VE",Location:"Maracaibo",WOEID:395270,Continent:"South America",Country:"Venezuela"},
  {ID:456,CountryCode:"VE",Location:"Maracay",WOEID:395271,Continent:"South America",Country:"Venezuela"},
  {ID:457,CountryCode:"VE",Location:"Maturín",WOEID:468384,Continent:"South America",Country:"Venezuela"},
  {ID:458,CountryCode:"VE",Location:"Turmero",WOEID:395277,Continent:"South America",Country:"Venezuela"},
  {ID:459,CountryCode:"VE",Location:"Valencia",WOEID:395272,Continent:"South America",Country:"Venezuela"},
  {ID:460,CountryCode:"VE",Location:"Venezuela",WOEID:23424982,Continent:"South America",Country:"Venezuela"},
  {ID:461,CountryCode:"VN",Location:"Can Tho",WOEID:1252351,Continent:"Asia",Country:"Viet Nam"},
  {ID:462,CountryCode:"VN",Location:"Da Nang",WOEID:1252376,Continent:"Asia",Country:"Viet Nam"},
  {ID:463,CountryCode:"VN",Location:"Hai Phong",WOEID:1236690,Continent:"Asia",Country:"Viet Nam"},
  {ID:464,CountryCode:"VN",Location:"Hanoi",WOEID:1236594,Continent:"Asia",Country:"Viet Nam"},
  {ID:465,CountryCode:"VN",Location:"Ho Chi Minh City",WOEID:1252431,Continent:"Asia",Country:"Viet Nam"},
  {ID:466,CountryCode:"VN",Location:"Vietnam",WOEID:23424984,Continent:"Asia",Country:"Viet Nam"}
]

export default CountryData;