const CountryData = [
  {ID:1,Location:"Algeria",WOEID:23424740,CountryCode:"DZ",Continent:"Africa",Country:"Algeria"},
  {ID:2,Location:"Algiers",WOEID:1253079,CountryCode:"DZ",Continent:"Africa",Country:"Algeria"},
  {ID:3,Location:"Argentina",WOEID:23424747,CountryCode:"AR",Continent:"America",Country:"Argentina"},
  {ID:4,Location:"Buenos Aires",WOEID:468739,CountryCode:"AR",Continent:"America",Country:"Argentina"},
  {ID:5,Location:"Córdoba",WOEID:466861,CountryCode:"AR",Continent:"America",Country:"Argentina"},
  {ID:6,Location:"Mendoza",WOEID:332471,CountryCode:"AR",Continent:"America",Country:"Argentina"},
  {ID:7,Location:"Rosario",WOEID:466862,CountryCode:"AR",Continent:"America",Country:"Argentina"},
  {ID:8,Location:"Adelaide",WOEID:1099805,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:9,Location:"Australia",WOEID:23424748,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:10,Location:"Brisbane",WOEID:1100661,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:11,Location:"Canberra",WOEID:1100968,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:12,Location:"Darwin",WOEID:1101597,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:13,Location:"Melbourne",WOEID:1103816,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:14,Location:"Perth",WOEID:1098081,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:15,Location:"Sydney",WOEID:1105779,CountryCode:"AU",Continent:"Australia",Country:"Australia"},
  {ID:16,Location:"Austria",WOEID:23424750,CountryCode:"AT",Continent:"Europe",Country:"Austria"},
  {ID:17,Location:"Vienna",WOEID:551801,CountryCode:"AT",Continent:"Europe",Country:"Austria"},
  {ID:18,Location:"Bahrain",WOEID:23424753,CountryCode:"BH",Continent:"Asia",Country:"Bahrain"},
  {ID:19,Location:"Belarus",WOEID:23424765,CountryCode:"BY",Continent:"Europe",Country:"Belarus"},
  {ID:20,Location:"Brest",WOEID:824382,CountryCode:"BY",Continent:"Europe",Country:"Belarus"},
  {ID:21,Location:"Gomel",WOEID:825978,CountryCode:"BY",Continent:"Europe",Country:"Belarus"},
  {ID:22,Location:"Grodno",WOEID:825848,CountryCode:"BY",Continent:"Europe",Country:"Belarus"},
  {ID:23,Location:"Minsk",WOEID:834463,CountryCode:"BY",Continent:"Europe",Country:"Belarus"},
  {ID:24,Location:"Belgium",WOEID:23424757,CountryCode:"BE",Continent:"Europe",Country:"Belgium"},
  {ID:25,Location:"Belém",WOEID:455820,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:26,Location:"Belo Horizonte",WOEID:455821,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:27,Location:"Brasília",WOEID:455819,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:28,Location:"Brazil",WOEID:23424768,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:29,Location:"Campinas",WOEID:455828,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:30,Location:"Curitiba",WOEID:455822,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:31,Location:"Fortaleza",WOEID:455830,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:32,Location:"Goiânia",WOEID:455831,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:33,Location:"Guarulhos",WOEID:455867,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:34,Location:"Manaus",WOEID:455833,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:35,Location:"Porto Alegre",WOEID:455823,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:36,Location:"Recife",WOEID:455824,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:37,Location:"Rio de Janeiro",WOEID:455825,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:38,Location:"Salvador",WOEID:455826,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:39,Location:"São Luís",WOEID:455834,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:40,Location:"São Paulo",WOEID:455827,CountryCode:"BR",Continent:"America",Country:"Brazil"},
  {ID:41,Location:"Calgary",WOEID:8775,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:42,Location:"Canada",WOEID:23424775,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:43,Location:"Edmonton",WOEID:8676,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:44,Location:"Montreal",WOEID:3534,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:45,Location:"Ottawa",WOEID:3369,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:46,Location:"Quebec",WOEID:3444,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:47,Location:"Toronto",WOEID:4118,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:48,Location:"Vancouver",WOEID:9807,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:49,Location:"Winnipeg",WOEID:2972,CountryCode:"CA",Continent:"America",Country:"Canada"},
  {ID:50,Location:"Chile",WOEID:23424782,CountryCode:"CL",Continent:"America",Country:"Chile"},
  {ID:51,Location:"Concepcion",WOEID:349860,CountryCode:"CL",Continent:"America",Country:"Chile"},
  {ID:52,Location:"Santiago",WOEID:349859,CountryCode:"CL",Continent:"America",Country:"Chile"},
  {ID:53,Location:"Valparaiso",WOEID:349861,CountryCode:"CL",Continent:"America",Country:"Chile"},
  {ID:54,Location:"Barranquilla",WOEID:368151,CountryCode:"CO",Continent:"America",Country:"Colombia"},
  {ID:55,Location:"Bogotá",WOEID:368148,CountryCode:"CO",Continent:"America",Country:"Colombia"},
  {ID:56,Location:"Cali",WOEID:368149,CountryCode:"CO",Continent:"America",Country:"Colombia"},
  {ID:57,Location:"Colombia",WOEID:23424787,CountryCode:"CO",Continent:"America",Country:"Colombia"},
  {ID:58,Location:"Medellín",WOEID:368150,CountryCode:"CO",Continent:"America",Country:"Colombia"},
  {ID:59,Location:"Denmark",WOEID:23424796,CountryCode:"DK",Continent:"Europe",Country:"Denmark"},
  {ID:60,Location:"Dominican Republic",WOEID:23424800,CountryCode:"DO",Continent:"America",Country:"Dominican Republic"},
  {ID:61,Location:"Santo Domingo",WOEID:76456,CountryCode:"DO",Continent:"America",Country:"Dominican Republic"},
  {ID:62,Location:"Ecuador",WOEID:23424801,CountryCode:"EC",Continent:"America",Country:"Ecuador"},
  {ID:63,Location:"Guayaquil",WOEID:375733,CountryCode:"EC",Continent:"America",Country:"Ecuador"},
  {ID:64,Location:"Quito",WOEID:375732,CountryCode:"EC",Continent:"America",Country:"Ecuador"},
  {ID:65,Location:"Alexandria",WOEID:1522006,CountryCode:"EG",Continent:"Africa",Country:"Egypt"},
  {ID:66,Location:"Cairo",WOEID:1521894,CountryCode:"EG",Continent:"Africa",Country:"Egypt"},
  {ID:67,Location:"Egypt",WOEID:23424802,CountryCode:"EG",Continent:"Africa",Country:"Egypt"},
  {ID:68,Location:"Giza",WOEID:1521643,CountryCode:"EG",Continent:"Africa",Country:"Egypt"},
  {ID:69,Location:"Bordeaux",WOEID:580778,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:70,Location:"France",WOEID:23424819,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:71,Location:"Lille",WOEID:608105,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:72,Location:"Lyon",WOEID:609125,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:73,Location:"Marseille",WOEID:610264,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:74,Location:"Montpellier",WOEID:612977,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:75,Location:"Nantes",WOEID:613858,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:76,Location:"Paris",WOEID:615702,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:77,Location:"Rennes",WOEID:619163,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:78,Location:"Strasbourg",WOEID:627791,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:79,Location:"Toulouse",WOEID:628886,CountryCode:"FR",Continent:"Europe",Country:"France"},
  {ID:80,Location:"Berlin",WOEID:638242,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:81,Location:"Bremen",WOEID:641142,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:82,Location:"Cologne",WOEID:667931,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:83,Location:"Dortmund",WOEID:645458,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:84,Location:"Dresden",WOEID:645686,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:85,Location:"Dusseldorf",WOEID:646099,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:86,Location:"Essen",WOEID:648820,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:87,Location:"Frankfurt",WOEID:650272,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:88,Location:"Germany",WOEID:23424829,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:89,Location:"Hamburg",WOEID:656958,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:90,Location:"Leipzig",WOEID:671072,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:91,Location:"Munich",WOEID:676757,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:92,Location:"Stuttgart",WOEID:698064,CountryCode:"DE",Continent:"Europe",Country:"Germany"},
  {ID:93,Location:"Accra",WOEID:1326075,CountryCode:"GH",Continent:"Africa",Country:"Ghana"},
  {ID:94,Location:"Ghana",WOEID:23424824,CountryCode:"GH",Continent:"Africa",Country:"Ghana"},
  {ID:95,Location:"Kumasi",WOEID:1330595,CountryCode:"GH",Continent:"Africa",Country:"Ghana"},
  {ID:96,Location:"Athens",WOEID:946738,CountryCode:"GR",Continent:"Europe",Country:"Greece"},
  {ID:97,Location:"Greece",WOEID:23424833,CountryCode:"GR",Continent:"Europe",Country:"Greece"},
  {ID:98,Location:"Thessaloniki",WOEID:963291,CountryCode:"GR",Continent:"Europe",Country:"Greece"},
  {ID:99,Location:"Guatemala",WOEID:23424834,CountryCode:"GT",Continent:"America",Country:"Guatemala"},
  {ID:100,Location:"Guatemala City",WOEID:83123,CountryCode:"GT",Continent:"America",Country:"Guatemala"},
  {ID:101,Location:"Ahmedabad",WOEID:2295402,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:102,Location:"Amritsar",WOEID:2295388,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:103,Location:"Bangalore",WOEID:2295420,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:104,Location:"Bhopal",WOEID:2295407,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:105,Location:"Chennai",WOEID:2295424,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:106,Location:"Delhi",WOEID:20070458,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:107,Location:"Hyderabad",WOEID:2295414,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:108,Location:"India",WOEID:23424848,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:109,Location:"Indore",WOEID:2295408,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:110,Location:"Jaipur",WOEID:2295401,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:111,Location:"Kanpur",WOEID:2295378,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:112,Location:"Kolkata",WOEID:2295386,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:113,Location:"Lucknow",WOEID:2295377,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:114,Location:"Mumbai",WOEID:2295411,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:115,Location:"Nagpur",WOEID:2282863,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:116,Location:"Patna",WOEID:2295381,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:117,Location:"Pune",WOEID:2295412,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:118,Location:"Rajkot",WOEID:2295404,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:119,Location:"Ranchi",WOEID:2295383,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:120,Location:"Srinagar",WOEID:2295387,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:121,Location:"Surat",WOEID:2295405,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:122,Location:"Thane",WOEID:2295410,CountryCode:"IN",Continent:"Asia",Country:"India"},
  {ID:123,Location:"Bandung",WOEID:1047180,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:124,Location:"Bekasi",WOEID:1030077,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:125,Location:"Depok",WOEID:1032539,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:126,Location:"Indonesia",WOEID:23424846,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:127,Location:"Jakarta",WOEID:1047378,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:128,Location:"Makassar",WOEID:1046138,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:129,Location:"Medan",WOEID:1047908,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:130,Location:"Palembang",WOEID:1048059,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:131,Location:"Pekanbaru",WOEID:1040779,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:132,Location:"Semarang",WOEID:1048324,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:133,Location:"Surabaya",WOEID:1044316,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:134,Location:"Tangerang",WOEID:1048536,CountryCode:"ID",Continent:"Asia",Country:"Indonesia"},
  {ID:135,Location:"Cork",WOEID:560472,CountryCode:"IE",Continent:"Europe",Country:"Ireland"},
  {ID:136,Location:"Dublin",WOEID:560743,CountryCode:"IE",Continent:"Europe",Country:"Ireland"},
  {ID:137,Location:"Galway",WOEID:560912,CountryCode:"IE",Continent:"Europe",Country:"Ireland"},
  {ID:138,Location:"Ireland",WOEID:23424803,CountryCode:"IE",Continent:"Europe",Country:"Ireland"},
  {ID:139,Location:"Haifa",WOEID:1967449,CountryCode:"IL",Continent:"Asia",Country:"Israel"},
  {ID:140,Location:"Israel",WOEID:23424852,CountryCode:"IL",Continent:"Asia",Country:"Israel"},
  {ID:141,Location:"Jerusalem",WOEID:1968222,CountryCode:"IL",Continent:"Asia",Country:"Israel"},
  {ID:142,Location:"Tel Aviv",WOEID:1968212,CountryCode:"IL",Continent:"Asia",Country:"Israel"},
  {ID:143,Location:"Bologna",WOEID:711080,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:144,Location:"Genoa",WOEID:716085,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:145,Location:"Italy",WOEID:23424853,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:146,Location:"Milan",WOEID:718345,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:147,Location:"Naples",WOEID:719258,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:148,Location:"Palermo",WOEID:719846,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:149,Location:"Rome",WOEID:721943,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:150,Location:"Turin",WOEID:725003,CountryCode:"IT",Continent:"Europe",Country:"Italy"},
  {ID:151,Location:"Chiba",WOEID:1117034,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:152,Location:"Fukuoka",WOEID:1117099,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:153,Location:"Hamamatsu",WOEID:1117155,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:154,Location:"Hiroshima",WOEID:1117227,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:155,Location:"Japan",WOEID:23424856,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:156,Location:"Kawasaki",WOEID:1117502,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:157,Location:"Kitakyushu",WOEID:1110809,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:158,Location:"Kobe",WOEID:1117545,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:159,Location:"Kumamoto",WOEID:1117605,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:160,Location:"Kyoto",WOEID:15015372,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:161,Location:"Nagoya",WOEID:1117817,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:162,Location:"Niigata",WOEID:1117881,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:163,Location:"Okayama",WOEID:90036018,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:164,Location:"Okinawa",WOEID:2345896,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:165,Location:"Osaka",WOEID:15015370,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:166,Location:"Sagamihara",WOEID:1118072,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:167,Location:"Saitama",WOEID:1116753,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:168,Location:"Sapporo",WOEID:1118108,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:169,Location:"Sendai",WOEID:1118129,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:170,Location:"Takamatsu",WOEID:1118285,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:171,Location:"Tokyo",WOEID:1118370,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:172,Location:"Yokohama",WOEID:1118550,CountryCode:"JP",Continent:"Asia",Country:"Japan"},
  {ID:173,Location:"Amman",WOEID:1968902,CountryCode:"JO",Continent:"Asia",Country:"Jordan"},
  {ID:174,Location:"Jordan",WOEID:23424860,CountryCode:"JO",Continent:"Asia",Country:"Jordan"},
  {ID:175,Location:"Kenya",WOEID:23424863,CountryCode:"KE",Continent:"Africa",Country:"Kenya"},
  {ID:176,Location:"Mombasa",WOEID:1528335,CountryCode:"KE",Continent:"Africa",Country:"Kenya"},
  {ID:177,Location:"Nairobi",WOEID:1528488,CountryCode:"KE",Continent:"Africa",Country:"Kenya"},
  {ID:178,Location:"Kuwait",WOEID:23424870,CountryCode:"KW",Continent:"Asia",Country:"Kuwait"},
  {ID:179,Location:"Latvia",WOEID:23424874,CountryCode:"LV",Continent:"Europe",Country:"Latvia"},
  {ID:180,Location:"Riga",WOEID:854823,CountryCode:"LV",Continent:"Europe",Country:"Latvia"},
  {ID:181,Location:"Lebanon",WOEID:23424873,CountryCode:"LB",Continent:"Asia",Country:"Lebanon"},
  {ID:182,Location:"Hulu Langat",WOEID:56013645,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:183,Location:"Ipoh",WOEID:1154679,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:184,Location:"Johor Bahru",WOEID:1154698,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:185,Location:"Kajang",WOEID:1141268,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:186,Location:"Klang",WOEID:1154726,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:187,Location:"Kuala Lumpur",WOEID:1154781,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:188,Location:"Malaysia",WOEID:23424901,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:189,Location:"Petaling",WOEID:56013632,CountryCode:"MY",Continent:"Asia",Country:"Malaysia"},
  {ID:190,Location:"Acapulco",WOEID:110978,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:191,Location:"Aguascalientes",WOEID:111579,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:192,Location:"Chihuahua",WOEID:115958,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:193,Location:"Ciudad Juarez",WOEID:116556,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:194,Location:"Culiacán",WOEID:117994,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:195,Location:"Ecatepec de Morelos",WOEID:118466,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:196,Location:"Guadalajara",WOEID:124162,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:197,Location:"Hermosillo",WOEID:124785,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:198,Location:"León",WOEID:131068,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:199,Location:"Mérida",WOEID:133327,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:200,Location:"Mexicali",WOEID:133475,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:201,Location:"Mexico",WOEID:23424900,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:202,Location:"Mexico City",WOEID:116545,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:203,Location:"Monterrey",WOEID:134047,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:204,Location:"Morelia",WOEID:134091,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:205,Location:"Naucalpan de Juárez",WOEID:134395,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:206,Location:"Nezahualcóyotl",WOEID:116564,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:207,Location:"Puebla",WOEID:137612,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:208,Location:"Querétaro",WOEID:138045,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:209,Location:"Saltillo",WOEID:141272,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:210,Location:"San Luis Potosí",WOEID:144265,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:211,Location:"Tijuana",WOEID:149361,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:212,Location:"Toluca",WOEID:149769,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:213,Location:"Zapopan",WOEID:151582,CountryCode:"MX",Continent:"America",Country:"Mexico"},
  {ID:214,Location:"Amsterdam",WOEID:727232,CountryCode:"NL",Continent:"Europe",Country:"Netherlands"},
  {ID:215,Location:"Den Haag",WOEID:726874,CountryCode:"NL",Continent:"Europe",Country:"Netherlands"},
  {ID:216,Location:"Netherlands",WOEID:23424909,CountryCode:"NL",Continent:"Europe",Country:"Netherlands"},
  {ID:217,Location:"Rotterdam",WOEID:733075,CountryCode:"NL",Continent:"Europe",Country:"Netherlands"},
  {ID:218,Location:"Utrecht",WOEID:734047,CountryCode:"NL",Continent:"Europe",Country:"Netherlands"},
  {ID:219,Location:"Auckland",WOEID:2348079,CountryCode:"NZ",Continent:"Australia",Country:"New Zealand"},
  {ID:220,Location:"New Zealand",WOEID:23424916,CountryCode:"NZ",Continent:"Australia",Country:"New Zealand"},
  {ID:221,Location:"Benin City",WOEID:1387660,CountryCode:"NG",Continent:"Africa",Country:"Nigeria"},
  {ID:222,Location:"Ibadan",WOEID:1393672,CountryCode:"NG",Continent:"Africa",Country:"Nigeria"},
  {ID:223,Location:"Kaduna",WOEID:1396439,CountryCode:"NG",Continent:"Africa",Country:"Nigeria"},
  {ID:224,Location:"Kano",WOEID:1396803,CountryCode:"NG",Continent:"Africa",Country:"Nigeria"},
  {ID:225,Location:"Lagos",WOEID:1398823,CountryCode:"NG",Continent:"Africa",Country:"Nigeria"},
  {ID:226,Location:"Nigeria",WOEID:23424908,CountryCode:"NG",Continent:"Africa",Country:"Nigeria"},
  {ID:227,Location:"Port Harcourt",WOEID:1404447,CountryCode:"NG",Continent:"Africa",Country:"Nigeria"},
  {ID:228,Location:"Bergen",WOEID:857105,CountryCode:"NO",Continent:"Europe",Country:"Norway"},
  {ID:229,Location:"Norway",WOEID:23424910,CountryCode:"NO",Continent:"Europe",Country:"Norway"},
  {ID:230,Location:"Oslo",WOEID:862592,CountryCode:"NO",Continent:"Europe",Country:"Norway"},
  {ID:231,Location:"Muscat",WOEID:2268284,CountryCode:"OM",Continent:"Asia",Country:"Oman"},
  {ID:232,Location:"Oman",WOEID:23424898,CountryCode:"OM",Continent:"Asia",Country:"Oman"},
  {ID:233,Location:"Faisalabad",WOEID:2211574,CountryCode:"PK",Continent:"Asia",Country:"Pakistan"},
  {ID:234,Location:"Karachi",WOEID:2211096,CountryCode:"PK",Continent:"Asia",Country:"Pakistan"},
  {ID:235,Location:"Lahore",WOEID:2211177,CountryCode:"PK",Continent:"Asia",Country:"Pakistan"},
  {ID:236,Location:"Multan",WOEID:2211269,CountryCode:"PK",Continent:"Asia",Country:"Pakistan"},
  {ID:237,Location:"Pakistan",WOEID:23424922,CountryCode:"PK",Continent:"Asia",Country:"Pakistan"},
  {ID:238,Location:"Rawalpindi",WOEID:2211387,CountryCode:"PK",Continent:"Asia",Country:"Pakistan"},
  {ID:239,Location:"Panama",WOEID:23424924,CountryCode:"PA",Continent:"America",Country:"Panama"},
  {ID:240,Location:"Lima",WOEID:418440,CountryCode:"PE",Continent:"America",Country:"Peru"},
  {ID:241,Location:"Peru",WOEID:23424919,CountryCode:"PE",Continent:"America",Country:"Peru"},
  {ID:242,Location:"Antipolo",WOEID:1198785,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:243,Location:"Cagayan de Oro",WOEID:1199002,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:244,Location:"Calocan",WOEID:1167715,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:245,Location:"Cebu City",WOEID:1199079,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:246,Location:"Davao City",WOEID:1199136,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:247,Location:"Makati",WOEID:1180689,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:248,Location:"Manila",WOEID:1199477,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:249,Location:"Pasig",WOEID:1187115,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:250,Location:"Philippines",WOEID:23424934,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:251,Location:"Quezon City",WOEID:1199682,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:252,Location:"Taguig",WOEID:1195098,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:253,Location:"Zamboanga City",WOEID:1199980,CountryCode:"PH",Continent:"Asia",Country:"Philippines"},
  {ID:254,Location:"Gdańsk",WOEID:493417,CountryCode:"PL",Continent:"Europe",Country:"Poland"},
  {ID:255,Location:"Kraków",WOEID:502075,CountryCode:"PL",Continent:"Europe",Country:"Poland"},
  {ID:256,Location:"Lodz",WOEID:505120,CountryCode:"PL",Continent:"Europe",Country:"Poland"},
  {ID:257,Location:"Poland",WOEID:23424923,CountryCode:"PL",Continent:"Europe",Country:"Poland"},
  {ID:258,Location:"Poznań",WOEID:514048,CountryCode:"PL",Continent:"Europe",Country:"Poland"},
  {ID:259,Location:"Warsaw",WOEID:523920,CountryCode:"PL",Continent:"Europe",Country:"Poland"},
  {ID:260,Location:"Wroclaw",WOEID:526363,CountryCode:"PL",Continent:"Europe",Country:"Poland"},
  {ID:261,Location:"Portugal",WOEID:23424925,CountryCode:"PT",Continent:"Europe",Country:"Portugal"},
  {ID:262,Location:"Puerto Rico",WOEID:23424935,CountryCode:"PR",Continent:"America",Country:"Puerto Rico"},
  {ID:263,Location:"Qatar",WOEID:23424930,CountryCode:"QA",Continent:"Asia",Country:"Qatar"},
  {ID:264,Location:"Chelyabinsk",WOEID:1997422,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:265,Location:"Irkutsk",WOEID:2121040,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:266,Location:"Kazan",WOEID:2121267,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:267,Location:"Khabarovsk",WOEID:2018708,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:268,Location:"Krasnodar",WOEID:2028717,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:269,Location:"Krasnoyarsk",WOEID:2029043,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:270,Location:"Moscow",WOEID:2122265,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:271,Location:"Nizhny Novgorod",WOEID:2122471,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:272,Location:"Novosibirsk",WOEID:2122541,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:273,Location:"Omsk",WOEID:2122641,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:274,Location:"Perm",WOEID:2122814,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:275,Location:"Rostov-on-Don",WOEID:2123177,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:276,Location:"Russia",WOEID:23424936,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:277,Location:"Saint Petersburg",WOEID:2123260,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:278,Location:"Samara",WOEID:2077746,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:279,Location:"Ufa",WOEID:2124045,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:280,Location:"Vladivostok",WOEID:2124288,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:281,Location:"Volgograd",WOEID:2124298,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:282,Location:"Voronezh",WOEID:2108210,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:283,Location:"Yekaterinburg",WOEID:2112237,CountryCode:"RU",Continent:"Asia",Country:"Russian Federation"},
  {ID:284,Location:"Ahsa",WOEID:56120136,CountryCode:"SA",Continent:"Asia",Country:"Saudi Arabia"},
  {ID:285,Location:"Dammam",WOEID:1939574,CountryCode:"SA",Continent:"Asia",Country:"Saudi Arabia"},
  {ID:286,Location:"Jeddah",WOEID:1939873,CountryCode:"SA",Continent:"Asia",Country:"Saudi Arabia"},
  {ID:287,Location:"Mecca",WOEID:1939897,CountryCode:"SA",Continent:"Asia",Country:"Saudi Arabia"},
  {ID:288,Location:"Medina",WOEID:1937801,CountryCode:"SA",Continent:"Asia",Country:"Saudi Arabia"},
  {ID:289,Location:"Riyadh",WOEID:1939753,CountryCode:"SA",Continent:"Asia",Country:"Saudi Arabia"},
  {ID:290,Location:"Saudi Arabia",WOEID:23424938,CountryCode:"SA",Continent:"Asia",Country:"Saudi Arabia"},
  {ID:291,Location:"Singapore",WOEID:1062617,CountryCode:"SG",Continent:"Asia",Country:"Singapore"},
  {ID:292,Location:"Singapore",WOEID:23424948,CountryCode:"SG",Continent:"Asia",Country:"Singapore"},
  {ID:293,Location:"Cape Town",WOEID:1591691,CountryCode:"ZA",Continent:"Africa",Country:"South Africa"},
  {ID:294,Location:"Durban",WOEID:1580913,CountryCode:"ZA",Continent:"Africa",Country:"South Africa"},
  {ID:295,Location:"Johannesburg",WOEID:1582504,CountryCode:"ZA",Continent:"Africa",Country:"South Africa"},
  {ID:296,Location:"Port Elizabeth",WOEID:1586614,CountryCode:"ZA",Continent:"Africa",Country:"South Africa"},
  {ID:297,Location:"Pretoria",WOEID:1586638,CountryCode:"ZA",Continent:"Africa",Country:"South Africa"},
  {ID:298,Location:"South Africa",WOEID:23424942,CountryCode:"ZA",Continent:"Africa",Country:"South Africa"},
  {ID:299,Location:"Soweto",WOEID:1587677,CountryCode:"ZA",Continent:"Africa",Country:"South Africa"},
  {ID:300,Location:"Ansan",WOEID:1132444,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:301,Location:"Bucheon",WOEID:1132445,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:302,Location:"Busan",WOEID:1132447,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:303,Location:"Changwon",WOEID:1132449,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:304,Location:"Daegu",WOEID:1132466,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:305,Location:"Daejeon",WOEID:2345975,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:306,Location:"Goyang",WOEID:1130853,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:307,Location:"Gwangju",WOEID:1132481,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:308,Location:"Incheon",WOEID:1132496,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:309,Location:"Korea",WOEID:23424868,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:310,Location:"Seongnam",WOEID:1132559,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:311,Location:"Seoul",WOEID:1132599,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:312,Location:"Suwon",WOEID:1132567,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:313,Location:"Ulsan",WOEID:1132578,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:314,Location:"Yongin",WOEID:1132094,CountryCode:"KR",Continent:"Asia",Country:"South Korea"},
  {ID:315,Location:"Barcelona",WOEID:753692,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:316,Location:"Bilbao",WOEID:754542,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:317,Location:"Las Palmas",WOEID:764814,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:318,Location:"Madrid",WOEID:766273,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:319,Location:"Malaga",WOEID:766356,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:320,Location:"Murcia",WOEID:768026,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:321,Location:"Palma",WOEID:769293,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:322,Location:"Seville",WOEID:774508,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:323,Location:"Spain",WOEID:23424950,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:324,Location:"Valencia",WOEID:776688,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:325,Location:"Zaragoza",WOEID:779063,CountryCode:"ES",Continent:"Europe",Country:"Spain"},
  {ID:326,Location:"Gothenburg",WOEID:890869,CountryCode:"SE",Continent:"Europe",Country:"Sweden"},
  {ID:327,Location:"Stockholm",WOEID:906057,CountryCode:"SE",Continent:"Europe",Country:"Sweden"},
  {ID:328,Location:"Sweden",WOEID:23424954,CountryCode:"SE",Continent:"Europe",Country:"Sweden"},
  {ID:329,Location:"Geneva",WOEID:782538,CountryCode:"CH",Continent:"Europe",Country:"Switzerland"},
  {ID:330,Location:"Lausanne",WOEID:783058,CountryCode:"CH",Continent:"Europe",Country:"Switzerland"},
  {ID:331,Location:"Switzerland",WOEID:23424957,CountryCode:"CH",Continent:"Europe",Country:"Switzerland"},
  {ID:332,Location:"Zurich",WOEID:784794,CountryCode:"CH",Continent:"Europe",Country:"Switzerland"},
  {ID:333,Location:"Bangkok",WOEID:1225448,CountryCode:"TH",Continent:"Asia",Country:"Thailand"},
  {ID:334,Location:"Thailand",WOEID:23424960,CountryCode:"TH",Continent:"Asia",Country:"Thailand"},
  {ID:335,Location:"Adana",WOEID:2343678,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:336,Location:"Ankara",WOEID:2343732,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:337,Location:"Antalya",WOEID:2343733,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:338,Location:"Bursa",WOEID:2343843,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:339,Location:"Diyarbakır",WOEID:2343932,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:340,Location:"Eskişehir",WOEID:2343980,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:341,Location:"Gaziantep",WOEID:2343999,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:342,Location:"Istanbul",WOEID:2344116,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:343,Location:"Izmir",WOEID:2344117,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:344,Location:"Kayseri",WOEID:2344174,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:345,Location:"Konya",WOEID:2344210,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:346,Location:"Mersin",WOEID:2323778,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:347,Location:"Turkey",WOEID:23424969,CountryCode:"TR",Continent:"Asia",Country:"Turkey"},
  {ID:348,Location:"Dnipropetrovsk",WOEID:918981,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:349,Location:"Donetsk",WOEID:919163,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:350,Location:"Kharkiv",WOEID:922137,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:351,Location:"Kyiv",WOEID:924938,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:352,Location:"Lviv",WOEID:924943,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:353,Location:"Odesa",WOEID:929398,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:354,Location:"Ukraine",WOEID:23424976,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:355,Location:"Zaporozhye",WOEID:939628,CountryCode:"UA",Continent:"Europe",Country:"Ukraine"},
  {ID:356,Location:"Abu Dhabi",WOEID:1940330,CountryCode:"AE",Continent:"Asia",Country:"United Arab Emirates"},
  {ID:357,Location:"Dubai",WOEID:1940345,CountryCode:"AE",Continent:"Asia",Country:"United Arab Emirates"},
  {ID:358,Location:"Sharjah",WOEID:1940119,CountryCode:"AE",Continent:"Asia",Country:"United Arab Emirates"},
  {ID:359,Location:"United Arab Emirates",WOEID:23424738,CountryCode:"AE",Continent:"Asia",Country:"United Arab Emirates"},
  {ID:360,Location:"Belfast",WOEID:44544,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:361,Location:"Birmingham",WOEID:12723,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:362,Location:"Blackpool",WOEID:12903,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:363,Location:"Bournemouth",WOEID:13383,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:364,Location:"Brighton",WOEID:13911,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:365,Location:"Bristol",WOEID:13963,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:366,Location:"Cardiff",WOEID:15127,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:367,Location:"Coventry",WOEID:17044,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:368,Location:"Derby",WOEID:18114,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:369,Location:"Edinburgh",WOEID:19344,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:370,Location:"Glasgow",WOEID:21125,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:371,Location:"Hull",WOEID:25211,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:372,Location:"Leeds",WOEID:26042,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:373,Location:"Leicester",WOEID:26062,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:374,Location:"Liverpool",WOEID:26734,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:375,Location:"London",WOEID:44418,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:376,Location:"Manchester",WOEID:28218,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:377,Location:"Middlesbrough",WOEID:28869,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:378,Location:"Newcastle",WOEID:30079,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:379,Location:"Nottingham",WOEID:30720,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:380,Location:"Plymouth",WOEID:32185,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:381,Location:"Portsmouth",WOEID:32452,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:382,Location:"Preston",WOEID:32566,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:383,Location:"Sheffield",WOEID:34503,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:384,Location:"Stoke-on-Trent",WOEID:36240,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:385,Location:"Swansea",WOEID:36758,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:386,Location:"United Kingdom",WOEID:23424975,CountryCode:"GB",Continent:"Europe",Country:"United Kingdom"},
  {ID:387,Location:"Albuquerque",WOEID:2352824,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:388,Location:"Atlanta",WOEID:2357024,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:389,Location:"Austin",WOEID:2357536,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:390,Location:"Baltimore",WOEID:2358820,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:391,Location:"Baton Rouge",WOEID:2359991,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:392,Location:"Birmingham",WOEID:2364559,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:393,Location:"Boston",WOEID:2367105,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:394,Location:"Charlotte",WOEID:2378426,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:395,Location:"Chicago",WOEID:2379574,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:396,Location:"Cincinnati",WOEID:2380358,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:397,Location:"Cleveland",WOEID:2381475,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:398,Location:"Colorado Springs",WOEID:2383489,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:399,Location:"Columbus",WOEID:2383660,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:400,Location:"Dallas-Ft. Worth",WOEID:2388929,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:401,Location:"Denver",WOEID:2391279,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:402,Location:"Detroit",WOEID:2391585,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:403,Location:"El Paso",WOEID:2397816,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:404,Location:"Fresno",WOEID:2407517,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:405,Location:"Greensboro",WOEID:2414469,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:406,Location:"Harrisburg",WOEID:2418046,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:407,Location:"Honolulu",WOEID:2423945,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:408,Location:"Houston",WOEID:2424766,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:409,Location:"Indianapolis",WOEID:2427032,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:410,Location:"Jackson",WOEID:2428184,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:411,Location:"Jacksonville",WOEID:2428344,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:412,Location:"Kansas City",WOEID:2430683,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:413,Location:"Las Vegas",WOEID:2436704,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:414,Location:"Long Beach",WOEID:2441472,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:415,Location:"Los Angeles",WOEID:2442047,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:416,Location:"Louisville",WOEID:2442327,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:417,Location:"Memphis",WOEID:2449323,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:418,Location:"Mesa",WOEID:2449808,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:419,Location:"Miami",WOEID:2450022,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:420,Location:"Milwaukee",WOEID:2451822,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:421,Location:"Minneapolis",WOEID:2452078,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:422,Location:"Nashville",WOEID:2457170,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:423,Location:"New Haven",WOEID:2458410,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:424,Location:"New Orleans",WOEID:2458833,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:425,Location:"New York",WOEID:2459115,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:426,Location:"Norfolk",WOEID:2460389,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:427,Location:"Oklahoma City",WOEID:2464592,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:428,Location:"Omaha",WOEID:2465512,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:429,Location:"Orlando",WOEID:2466256,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:430,Location:"Philadelphia",WOEID:2471217,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:431,Location:"Phoenix",WOEID:2471390,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:432,Location:"Pittsburgh",WOEID:2473224,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:433,Location:"Portland",WOEID:2475687,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:434,Location:"Providence",WOEID:2477058,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:435,Location:"Raleigh",WOEID:2478307,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:436,Location:"Richmond",WOEID:2480894,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:437,Location:"Sacramento",WOEID:2486340,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:438,Location:"Salt Lake City",WOEID:2487610,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:439,Location:"San Antonio",WOEID:2487796,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:440,Location:"San Diego",WOEID:2487889,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:441,Location:"San Francisco",WOEID:2487956,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:442,Location:"San Jose",WOEID:2488042,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:443,Location:"Seattle",WOEID:2490383,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:444,Location:"St. Louis",WOEID:2486982,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:445,Location:"Tallahassee",WOEID:2503713,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:446,Location:"Tampa",WOEID:2503863,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:447,Location:"Tucson",WOEID:2508428,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:448,Location:"United States",WOEID:23424977,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:449,Location:"Virginia Beach",WOEID:2512636,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:450,Location:"Washington",WOEID:2514815,CountryCode:"US",Continent:"America",Country:"United States of America"},
  {ID:451,Location:"Barcelona",WOEID:395273,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:452,Location:"Barquisimeto",WOEID:468382,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:453,Location:"Caracas",WOEID:395269,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:454,Location:"Ciudad Guayana",WOEID:395275,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:455,Location:"Maracaibo",WOEID:395270,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:456,Location:"Maracay",WOEID:395271,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:457,Location:"Maturín",WOEID:468384,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:458,Location:"Turmero",WOEID:395277,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:459,Location:"Valencia",WOEID:395272,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:460,Location:"Venezuela",WOEID:23424982,CountryCode:"VE",Continent:"America",Country:"Venezuela"},
  {ID:461,Location:"Can Tho",WOEID:1252351,CountryCode:"VN",Continent:"Asia",Country:"Viet Nam"},
  {ID:462,Location:"Da Nang",WOEID:1252376,CountryCode:"VN",Continent:"Asia",Country:"Viet Nam"},
  {ID:463,Location:"Hai Phong",WOEID:1236690,CountryCode:"VN",Continent:"Asia",Country:"Viet Nam"},
  {ID:464,Location:"Hanoi",WOEID:1236594,CountryCode:"VN",Continent:"Asia",Country:"Viet Nam"},
  {ID:465,Location:"Ho Chi Minh City",WOEID:1252431,CountryCode:"VN",Continent:"Asia",Country:"Viet Nam"},
  {ID:466,Location:"Vietnam",WOEID:23424984,CountryCode:"VN",Continent:"Asia",Country:"Viet Nam"}
]

export default CountryData;